name: Infraestructura deployment

on:
  push:
    branches: [main]

jobs:
  deploy-lab3-infra-and-restore:
    runs-on: windows-latest

    steps:
    - name: Checkout del repositorio
      uses: actions/checkout@v3

    - name: Login a Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.6.6

    - name: Crear archivo terraform.tfvars
      run: |
        echo "subscription_id = \"${{ secrets.SUBSCRIPTION_ID }}\"" > Proyecto/infra/terraform.tfvars
        echo "sqladmin_username = \"${{ secrets.SQL_USERNAME }}\"" >> Proyecto/infra/terraform.tfvars
        echo "sqladmin_password = \"${{ secrets.SQL_PASSWORD }}\"" >> Proyecto/infra/terraform.tfvars
        echo "resource_group_name = \"${{ secrets.RESOURCE_GROUP }}\"" >> Proyecto/infra/terraform.tfvars
        echo "location = \"${{ secrets.LOCATION }}\"" >> Proyecto/infra/terraform.tfvars

    - name: Terraform Init
      working-directory: Proyecto/infra
      run: terraform init

    - name: Terraform Plan
      working-directory: Proyecto/infra
      run: terraform plan -var-file="terraform.tfvars" -out="tfplan.binary"

    # -------------------------------
    # BLOQUE DE COSTOS
    # -------------------------------
    - name: Instalar Infracost y herramientas
      run: |
        choco install infracost -y
        choco install pandoc -y
        choco install miktex -y

    - name: Generar desglose de costos (tabla)
      run: |
        infracost breakdown --path=Proyecto/infra/tfplan.binary --format table

    - name: Generar desglose de costos (JSON)
      run: |
        infracost breakdown --path=Proyecto/infra/tfplan.binary --format json > Proyecto/infra/costos.json

    - name: Crear archivo costos.md
      shell: pwsh
      run: |
        $json = Get-Content -Raw Proyecto/infra/costos.json | ConvertFrom-Json
        $output = @("# Informe de Costos de Infraestructura - Proyecto Doc2Markdown`n`n## Recursos con Costo`n`n| Recurso | Componente | Cantidad | Unidad | Costo |`n|---------|------------|----------|--------|-------|")
        foreach ($r in $json.projects.breakdown.resources) {
          foreach ($c in $r.costComponents) {
            $qty = if ($c.monthlyQuantity) { $c.monthlyQuantity } else { "*Variable*" }
            $cost = if ($c.monthlyCost) { "$$($c.monthlyCost)" } else { "Depende del uso" }
            $output += "| $($r.name) | $($c.name) | $qty | $($c.unit) | $cost |"
          }
        }
        $output += "`n## Total: *$($json.projects.breakdown.totalMonthlyCost) USD/mes*"
        $output += "`n*Actualizado: $(Get-Date -Format 'yyyy-MM-dd')*"
        $output | Out-File Proyecto/infra/costos.md -Encoding utf8

    - name: Generar PDF de costos
      run: pandoc Proyecto/infra/costos.md -o Proyecto/infra/costos.pdf

    - name: Subir artefacto Informe de costos
      uses: actions/upload-artifact@v4
      with:
        name: informe-costos-infraestructura
        path: Proyecto/infra/costos.pdf

