name: Run GitHub Scraper and Save Artifact

on:
  workflow_dispatch:
  push:
    paths:
      - github_scraper/app.py
      - .github/workflows/github-scraper-artifact.yml

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install pandas PyGithub

      - name: Run GitHub Scraper
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT_SCRAPER }}
        run: python github_scraper/app.py

      - name: Upload data artifacts
        uses: actions/upload-artifact@v4
        with:
          name: github-scraper-data
          path: github_scraper/data/

      - name: Install sqlcmd
        run: |
          sudo apt-get update
          sudo ACCEPT_EULA=Y apt-get install -y mssql-tools unixodbc-dev

      - name: Run SQL script on Azure SQL
        env:
          AZURE_SQL_SERVER: ${{ secrets.AZURE_SQL_SERVER }}
          AZURE_SQL_DB: ${{ secrets.AZURE_SQL_DB_2 }}
          AZURE_SQL_USER: ${{ secrets.AZURE_SQL_USER }}
          AZURE_SQL_PASS: ${{ secrets.AZURE_SQL_PASS }}
        run: |
          /opt/mssql-tools/bin/sqlcmd -S "$AZURE_SQL_SERVER" -d "$AZURE_SQL_DB_2" -U "$AZURE_SQL_USER" -P "$AZURE_SQL_PASS" -i github_scraper/data/github_data_insert.sql