name: Release Automático

on:
  push:
    tags:
      - 'v*.*.*'   # Se ejecuta al subir un tag como v1.0.0

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Crear Release en GitHub
        uses: softprops/action-gh-release@v2
        with:
          name: "Release ${{ github.ref_name }}"
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
